version: '3'

services:
  web:
    image: python:3.10
    volumes:
      - .:/app
    working_dir: /app
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py telegram_bot_plays_three
    ports:
      - "8007:8007"